---
title: "SIR II"
author: "Prof. Mauro Rodriguez"
date: "2/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(deSolve)
#tamaño poblacional
N = 500
#estado inicial de los compartimentos
init <- c(S = 1-1e-6,
          I = 1e-6,
          R = 0)
#parámetros del modelo (coeficientes de las variables)
param <- c(beta = 1.4247,
           gamma = 0.14286)
#crear la función con las ODE
sir <- function(times, init, param) {
  with(as.list(c(init, param)), {
#ecuaciones diferenciales   
    dS <- -beta * S * I
    dI <-  beta * S * I - gamma * I
    dR <-                 gamma * I
#resultados de las tasas de cambio    
    return(list(c(dS, dI, dR)))
  })
}
#intervalo de tiempo y resolución
times <- seq(50, 150, by = 1)
#resolver el sistema de ecuaciones con función 'ode'
out <- ode(y = init, times = times, func = sir, parms = param)
#cambiar out a un data.frame
out <- as.data.frame(out*N) #aqui puede multiplicar 'out' por N
#eliminar la variable 'time' en out
out$time <- NULL
#mostrar 10 primeros datos
#head(out, 10)

#gráfica
matplot(x = times, y = out, type = "l",
        xlab = "Tiempo       Mauro R  Datos:JHU  RStudio", ylab = "Nuevos casos confirmados, Recuperados", main = "Modelo epidemiológico largo plazo para México",
        lwd = 1, lty = 1, bty = "l", col = 2:4)
#añadir leyenda de líneas
legend(90, 377.7, c("Susceptibles", "Nuevos casos confirmados (1er escenario pico 2-6 de mayo", "Recuperados"), 
       pch = 1, col = 2:4, bty = "n", cex = 1)
```



